[build]
  # Comando de construcción para compilar el proyecto Next.js
  command = "next build && next output: export"

  # Directorio donde Next.js generará los archivos para la implementación
  publish = "out"
